[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
luciene = "GWVfXsjLBfbLvHpuwXPR6jYsCPSCcbMXaKBZvNLM1bgJ"

[registry]
url = "https://localnet::8099"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

#[programs.devnet]
#luciene = "GWVfXsjLBfbLvHpuwXPR6jYsCPSCcbMXaKBZvNLM1bgJ"
#[registry]
#url = "https://api.apr.dev"

#[scripts]
#test = "cargo test"

