[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
luciene = "2ViX4tfo3HcFkwRBeDmBesq7kWrBJNAxpkNFsKpA9HLk"

[registry]
url = "http://127.0.0.1::8899"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

#[programs.devnet]
#luciene = "GWVfXsjLBfbLvHpuwXPR6jYsCPSCcbMXaKBZvNLM1bgJ"

#[registry]
#url = "https://api.apr.dev"

#[provider]
#cluster = "devnet"
#wallet = "~/.config/solana/id.json"

#[scripts]
#test = "cargo test"

