[env]
PROGRAM = "2ViX4tfo3HcFkwRBeDmBesq7kWrBJNAxpkNFsKpA9HLk"
NETWORK = "http://127.0.0.1:8899"
WALLET = "~/.config/solana/"
PROGRAM_MAINNET = "GWVfXsjLBfbLvHpuwXPR6jYsCPSCcbMXaKBZvNLM1bgJ"
NETWORK_MAINNET = "https://api.apr.dev"
